# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow1(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(391, 310)
        MainWindow.setStyleSheet("background-color: rgb(25, 25, 27);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.login = QtWidgets.QLineEdit(self.centralwidget)
        self.login.setGeometry(QtCore.QRect(10, 10, 181, 41))
        self.login.setStyleSheet("background-color: rgb(69, 70, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Fulbo\";")
        self.login.setObjectName("login")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, 70, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Fulbo")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.pushButton.setStyleSheet("background-color: rgb(69, 70, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Fulbo\";\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.ok = QtWidgets.QPushButton(self.centralwidget)
        self.ok.setGeometry(QtCore.QRect(190, 250, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Fulbo")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.ok.setFont(font)
        self.ok.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.ok.setStyleSheet("background-color: rgb(69, 70, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Fulbo\";\n"
"")
        self.ok.setObjectName("ok")
        self.cancel = QtWidgets.QPushButton(self.centralwidget)
        self.cancel.setGeometry(QtCore.QRect(280, 250, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Fulbo")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.cancel.setFont(font)
        self.cancel.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.cancel.setStyleSheet("background-color: rgb(69, 70, 72);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 10pt \"Fulbo\";\n"
"")
        self.cancel.setObjectName("cancel")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.login.setText(_translate("MainWindow", "Введите название"))
        self.pushButton.setText(_translate("MainWindow", "Выбрать изображение"))
        self.ok.setText(_translate("MainWindow", "ok"))
        self.cancel.setText(_translate("MainWindow", "cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
